# Generated by Django 5.2.1 on 2025-05-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
