# Generated by Django 5.2.1 on 2025-05-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_studentprofile_email_studentprofile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='coursenumber',
            field=models.IntegerField(default=100),
        ),
    ]
