# Generated by Django 5.2.1 on 2025-05-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_studentprofile_coursenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='favsubjects',
            field=models.CharField(default='', max_length=500),
        ),
    ]
