# Generated by Django 5.2.1 on 2025-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='quiz_highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
